export const INIT_RESERVATIONS = 'INIT_RESERVATIONS';
export const FIND_RESERVATIONS_FETCH = 'FIND_RESERVATIONS_FETCH';
export const DELETE_RESERVATIONS = 'DELETE_RESERVATIONS';
export const UPDATE_RESERVATIONS = 'UPDATE_RESERVATIONS';
